import { randomUUID } from "crypto"
import { mkdir, unlink, writeFile } from "fs/promises"
import path from "path"
import { NextResponse } from "next/server"
import { auditDownloadUpload, requireDownloadManager } from "@/lib/download-content-server"
import type { DownloadFile } from "@/lib/download-content"
const MAX = 20 * 1024 * 1024
const formats = { pdf: "application/pdf", docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation" } as const
const FORBIDDEN_EXTS = new Set(["exe", "dmg", "pkg", "app", "apk", "bat", "cmd", "sh", "js", "html", "htm", "svg", "zip", "rar", "7z", "docm", "xlsm", "pptm"]);

function safeName(name: string) { return name.normalize("NFKC").replace(/[\u0000-\u001f\u007f<>:"/\\|?*]/g, "-").replace(/\s+/g, " ").slice(0, 180) || "dokumen" }
function validSignature(bytes: Uint8Array, ext: keyof typeof formats) { return ext === "pdf" ? bytes.length >= 5 && String.fromCharCode(...bytes.slice(0, 5)) === "%PDF-" : bytes.length >= 4 && bytes[0] === 0x50 && bytes[1] === 0x4b && bytes[2] === 0x03 && bytes[3] === 0x04 }
export async function POST(request: Request) { let output = ""; try { const access = await requireDownloadManager(); if ("response" in access) return access.response; const value = (await request.formData()).get("file"); if (!(value instanceof File)) return NextResponse.json({ error: "File tidak ditemukan." }, { status: 400 }); if (value.size < 1 || value.size > MAX) return NextResponse.json({ error: "Ukuran file tidak valid." }, { status: 400 }); const parts = value.name.toLowerCase().split("."); const ext = parts.pop() as keyof typeof formats; if (parts.some(x => FORBIDDEN_EXTS.has(x) || Object.keys(formats).includes(x)) || !formats[ext] || value.type !== formats[ext]) return NextResponse.json({ error: "Format file tidak didukung atau tidak sesuai." }, { status: 400 }); const bytes = new Uint8Array(await value.arrayBuffer()); if (!validSignature(bytes, ext)) return NextResponse.json({ error: "Isi file tidak sesuai dengan formatnya." }, { status: 400 }); const filename = `${randomUUID()}.${ext}`; const directory = path.join(process.cwd(), "public", "uploads", "documents", "download-content"); await mkdir(directory, { recursive: true }); output = path.join(directory, filename); await writeFile(output, bytes, { flag: "wx" }); const file: DownloadFile = { path: `/uploads/documents/download-content/${filename}`, originalDisplayName: safeName(value.name), mimeType: formats[ext], fileSize: value.size, uploadedAt: new Date().toISOString() }; await auditDownloadUpload(access.user, ext.toUpperCase(), value.size); return NextResponse.json({ file }) } catch (error) { if (output) await unlink(output).catch(() => undefined); console.error("Download asset upload failed:", error); return NextResponse.json({ error: "Gagal mengunggah dokumen." }, { status: 500 }) } }
