"use client"

import { useCallback, useEffect, useState } from "react"
import { MemberLayout } from "@/components/member-area/member-shell"
import { Input } from "@/components/ui/input"

type Audit = { summary: string; category: string; sourceLabel: string; actorName: string; targetName: string; timestamp: string }
type Result = { entries: Audit[]; hasMore: boolean }
export default function AuditPage() {
  const [items, setItems] = useState<Audit[]>([]); const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [page, setPage] = useState(1); const [hasMore, setHasMore] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ page: String(page), limit: "20" }); if (query) params.set("search", query); if (category) params.set("category", category); const response = await fetch(`/api/audit?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Catatan audit gagal dimuat."); const data = await response.json() as Result;     setItems(data.entries); setHasMore(data.hasMore) } catch (cause) { setError(cause instanceof Error ? cause.message : "Terjadi kesalahan.") } finally { setLoading(false) } }, [category, page, query])
  useEffect(() => { const timeout = setTimeout(() => void load(), 250); return () => clearTimeout(timeout) }, [load])
  return <MemberLayout title="Audit Trail" breadcrumb="Member Area / Audit"><section className="mx-auto max-w-6xl rounded-2xl border bg-card p-5 sm:p-6"><div><h2 className="text-2xl font-bold">Catatan Audit</h2><p className="mt-1 text-sm text-muted-foreground">Riwayat sistem hanya-baca untuk penelusuran perubahan.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Input type="search" aria-label="Cari audit" placeholder="Cari pelaku atau ringkasan" value={query} onChange={(event) => { setQuery(event.target.value); setPage(1) }} />            <select aria-label="Filter kategori" value={category} onChange={(event) => { setCategory(event.target.value); setPage(1) }} className="min-h-10 rounded-md border bg-background px-3 text-sm">
              <option value="">Semua kategori</option>
              <option value="Akun">Akun</option>
              <option value="Profil">Profil</option>
              <option value="Keamanan">Keamanan</option>
              <option value="Akses">Akses</option>
              <option value="Notifikasi">Notifikasi</option>
            </select></div>{loading && !items.length ? <p className="py-10 text-center text-muted-foreground">Memuat audit...</p> : error ? <div role="alert" className="mt-5 rounded-xl bg-destructive/10 p-4 text-destructive">{error}<button className="ml-3 underline" onClick={() => void load()}>Coba lagi</button></div> : items.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Waktu</th><th className="p-3">Pelaku</th><th className="p-3">Ringkasan</th><th className="p-3">Target</th><th className="p-3">Kategori</th></tr></thead><tbody>              {items.map((item, index) => <tr key={index} className="border-b last:border-0"><td className="p-3 text-muted-foreground">{new Intl.DateTimeFormat("id-ID", { dateStyle: "short", timeStyle: "short" }).format(new Date(item.timestamp))}</td><td className="p-3 font-medium">{item.actorName}</td><td className="p-3"><span className="block font-medium">{item.summary}</span><span className="block text-xs text-muted-foreground">{item.sourceLabel}</span></td><td className="p-3">{item.targetName}</td><td className="p-3 text-muted-foreground">{item.category}</td></tr>)}</tbody></table></div> : <p className="py-10 text-center text-muted-foreground">Tidak ada catatan audit.</p>}<nav className="mt-5 flex justify-end gap-2" aria-label="Pagination audit"><button className="rounded-lg border px-3 py-2 text-sm disabled:opacity-50" disabled={page <= 1} onClick={() => setPage(page - 1)}>Sebelumnya</button><span className="px-3 py-2 text-sm">Halaman {page}</span><button className="rounded-lg border px-3 py-2 text-sm disabled:opacity-50" disabled={!hasMore} onClick={() => setPage(page + 1)}>Berikutnya</button></nav></section></MemberLayout>
}
