'use client';

import type { GorutMunfiq } from '@/features/gorut-v2/types';
import { formatDateShort, formatPhoneNumber, formatRupiah, getInitials } from '@/features/gorut-v2/formatters';
import { calculateMunfiqAverageMonthly, munfiqStatusLabels } from '@/features/gorut-v2/munfiq-options';
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@/components/ui/sheet';

export function MunfiqDetailDrawer({ open, munfiq, onClose, onEdit, onDelete, onNotice }: { open: boolean; munfiq: GorutMunfiq | null; onClose: () => void; onEdit: () => void; onDelete: () => void; onNotice: (message: string) => void }) {
  if (!munfiq) return null;
  const average = calculateMunfiqAverageMonthly(munfiq);
  const transactions = munfiq.lastDepositAt && munfiq.lastDepositAmount !== undefined
    ? [{ id: `${munfiq.id}-latest`, date: munfiq.lastDepositAt, amount: munfiq.lastDepositAmount }]
    : [];
  return <Sheet open={open} onOpenChange={(nextOpen) => { if (!nextOpen) onClose(); }}><SheetContent className="gorut-munfiq-drawer" aria-describedby="munfiq-detail-description"><SheetHeader className="gorut-drawer-header"><div className="gorut-munfiq-person"><span className="gorut-avatar">{getInitials(munfiq.name)}</span><span><SheetTitle>{munfiq.name}</SheetTitle><SheetDescription id="munfiq-detail-description">{munfiq.memberId}</SheetDescription></span></div><button type="button" className="gorut-button gorut-secondary-button" onClick={onEdit}>Edit</button></SheetHeader><div className="gorut-drawer-body"><DrawerSection title="Informasi Kontak"><dl><div><dt>Nomor HP</dt><dd>{formatPhoneNumber(munfiq.phone)}</dd></div><div><dt>Email</dt><dd>{munfiq.email || '-'}</dd></div><div><dt>Alamat</dt><dd>{munfiq.address}</dd></div></dl></DrawerSection><DrawerSection title="Wilayah & Penanggung Jawab"><dl><div><dt>Kecamatan / UPZIS</dt><dd>{munfiq.kecamatan}</dd></div><div><dt>Desa / Ranting</dt><dd>{munfiq.village}</dd></div><div><dt>Petugas PLPK</dt><dd>{munfiq.plpkName}<small>{munfiq.plpkId}</small></dd></div><div><dt>Status Munfiq</dt><dd><span className={`gorut-munfiq-status is-${munfiq.status}`}>{munfiqStatusLabels[munfiq.status]}</span></dd></div></dl></DrawerSection><DrawerSection title="Ringkasan Penghimpunan"><div className="gorut-summary-grid"><Summary label="Total Terkumpul" value={formatRupiah(munfiq.totalCollected)} /><Summary label="Rata-rata Bulanan" value={formatRupiah(average)} /><Summary label="Jumlah Setoran" value={`${munfiq.transactionCount} kali`} /></div></DrawerSection><DrawerSection title="Setoran Terakhir">{transactions.length ? <div className="gorut-drawer-transactions">{transactions.map((transaction) => <div key={transaction.id} className="gorut-drawer-transaction-row"><div><strong>{formatRupiah(transaction.amount)}</strong><small>{formatDateShort(transaction.date)}</small></div><span className="gorut-munfiq-status is-active">Tercatat</span></div>)}</div> : <p className="gorut-drawer-empty-text">Belum ada data setoran.</p>}</DrawerSection><DrawerSection title="Catatan">{munfiq.notes ? <p className="gorut-drawer-notes-text">{munfiq.notes}</p> : <p className="gorut-drawer-empty-text">Tidak ada catatan</p>}</DrawerSection></div><SheetFooter className="gorut-drawer-footer"><button type="button" className="gorut-button gorut-danger-button" onClick={onDelete}>Hapus</button><div><button type="button" className="gorut-button gorut-secondary-button" onClick={() => onNotice('Fitur transaksi akan dibuat pada batch berikutnya')}>Catat Transaksi</button><button type="button" className="gorut-button gorut-primary-button" onClick={onClose}>Tutup</button></div></SheetFooter></SheetContent></Sheet>;
}

function DrawerSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="gorut-drawer-section"><h3>{title}</h3>{children}</section>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="gorut-summary-metric"><small>{label}</small><strong>{value}</strong></div>; }
