"use client"

import { FormEvent, useEffect, useState } from "react"
import { MemberLayout } from "@/components/member-area/member-shell"
import { useAuth } from "@/lib/auth-context"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

type Audience = "all" | "role" | "user"
type Managed = { id: string; title: string; body: string; category: string; severity: string; audience: Audience; targetRole?: string | null; targetUserId?: string | null; expiresAt?: string | null; actionPath?: string | null; publishedAt: string; withdrawnAt: string | null; creatorName?: string | null }
type Result = { notifications: Managed[] }
export default function ManageNotificationsPage() {
  const { user, isLoading } = useAuth(); const [items, setItems] = useState<Managed[]>([]); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [category, setCategory] = useState("general"); const [severity, setSeverity] = useState("info"); const [audience, setAudience] = useState<Audience>("all"); const [target, setTarget] = useState(""); const [expiresAt, setExpiresAt] = useState(""); const [actionPath, setActionPath] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("")
  const load = async () => { try { const response = await fetch("/api/notifications/manage?limit=50", { cache: "no-store" }); if (!response.ok) throw new Error("Riwayat publikasi tidak dapat dimuat."); setItems((await response.json() as Result).notifications) } catch (cause) { setError(cause instanceof Error ? cause.message : "Terjadi kesalahan.") } }
  useEffect(() => { if (user?.role === "super_admin_pc") void load() }, [user])
  const publish = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); const payload = { title: title.trim(), body: body.trim(), category, severity, audience, ...(audience === "role" ? { targetRole: target } : {}), ...(audience === "user" ? { targetUserId: target } : {}), ...(expiresAt ? { expiresAt: new Date(expiresAt).toISOString() } : {}), ...(actionPath.trim() ? { actionPath: actionPath.trim() } : {}) }; try { const response = await fetch("/api/notifications/manage", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (response.status !== 201) throw new Error("Notifikasi gagal dipublikasikan."); setTitle(""); setBody(""); setTarget(""); setExpiresAt(""); setActionPath(""); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : "Terjadi kesalahan.") } finally { setBusy(false) } }
  const withdraw = async (id: string) => { setBusy(true); const response = await fetch(`/api/notifications/manage/${id}/withdraw`, { method: "PATCH" }); if (response.ok) await load(); else setError("Notifikasi gagal ditarik."); setBusy(false) }
  if (isLoading || !user) return <div className="min-h-screen bg-background" />
  if (user.role !== "super_admin_pc") return <MemberLayout title="Notifikasi" breadcrumb="Member Area / Notifikasi"><div role="alert" className="rounded-2xl border p-6">Halaman ini hanya tersedia untuk Super Admin PC.</div></MemberLayout>
  return <MemberLayout title="Kelola Notifikasi" breadcrumb="Member Area / Notifikasi"><div className="mx-auto grid max-w-6xl gap-6 lg:grid-cols-[1fr_1.35fr]"><form onSubmit={publish} className="h-fit space-y-4 rounded-2xl border bg-card p-6"><div><h2 className="text-xl font-bold">Publikasikan notifikasi</h2><p className="text-sm text-muted-foreground">Notifikasi langsung terbit setelah dikirim.</p></div><div><Label htmlFor="title">Judul</Label><Input id="title" required maxLength={120} value={title} onChange={(event) => setTitle(event.target.value)} /></div><div><Label htmlFor="body">Isi</Label><Textarea id="body" required maxLength={500} value={body} onChange={(event) => setBody(event.target.value)} /></div><div className="grid gap-4 sm:grid-cols-2"><Select label="Kategori" value={category} onChange={setCategory} options={["general", "security", "account", "access", "system"]} /><Select label="Severity" value={severity} onChange={setSeverity} options={["info", "success", "warning", "critical"]} /><Select label="Audiens" value={audience} onChange={(value) => { setAudience(value as Audience); setTarget("") }} options={["all", "role", "user"]} />{audience !== "all" && <div><Label htmlFor="target">{audience === "role" ? "Target role" : "ID pengguna"}</Label><Input id="target" required value={target} onChange={(event) => setTarget(event.target.value)} /></div>}<div><Label htmlFor="expires">Kedaluwarsa (opsional)</Label><Input id="expires" type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></div><div><Label htmlFor="action">Path aksi (opsional)</Label><Input id="action" placeholder="/member-area" value={actionPath} onChange={(event) => setActionPath(event.target.value)} /></div></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={busy}>{busy ? "Memproses..." : "Publikasikan"}</Button></form><section className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-bold">Riwayat publikasi</h2><div className="mt-4 space-y-3">{items.length ? items.map((item) => <article key={item.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{item.title}</h3><p className="mt-1 text-sm text-muted-foreground">{item.body}</p><p className="mt-2 text-xs text-muted-foreground">{item.category} · {item.audience}{item.targetRole ? `: ${item.targetRole}` : ""}{item.targetUserId ? `: ${item.targetUserId}` : ""} · {item.withdrawnAt ? "Ditarik" : "Terbit"}</p></div>{!item.withdrawnAt && <Button type="button" variant="outline" size="sm" disabled={busy} onClick={() => void withdraw(item.id)}>Tarik</Button>}</div></article>) : <p className="text-sm text-muted-foreground">Belum ada riwayat publikasi.</p>}</div></section></div></MemberLayout>
}
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="text-sm font-medium">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 min-h-10 w-full rounded-md border bg-background px-3">{options.map((option) => <option key={option}>{option}</option>)}</select></label> }
