"use client"

import { useEffect, useMemo, useState } from "react"
import Image from "next/image"
import { useRouter } from "next/navigation"
import { ArrowDown, ArrowUp, ImagePlus, Plus, RotateCcw, Save, Trash2 } from "lucide-react"
import { MemberLayout } from "@/components/landing-page/member-shell"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { useAuth } from "@/lib/auth-context"
import type { GalleryAsset, GalleryContent } from "@/lib/gallery-content"

export default function GalleryEditorPage() {
  const router = useRouter(); const { user, isLoading } = useAuth(); const [content, setContent] = useState<GalleryContent | null>(null); const [initial, setInitial] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [filter, setFilter] = useState("all")
  const dirty = content ? JSON.stringify(content) !== initial : false
  useEffect(() => { if (!isLoading) { if (!user) router.replace("/login?next=/dashboard/landing-page/galeri"); else if (user.role !== "super_admin_pc") router.replace("/dashboard") } }, [isLoading, router, user])
  useEffect(() => { if (user?.role !== "super_admin_pc") return; void fetch("/api/gallery-content/manage", { cache: "no-store" }).then(async response => { if (!response.ok) throw new Error("load"); const payload: { content: GalleryContent } = await response.json(); setContent(payload.content); setInitial(JSON.stringify(payload.content)) }).catch(error => { console.error("Gagal memuat editor galeri:", error); setMessage("Konten galeri belum dapat dimuat.") }) }, [user])
  useEffect(() => { const warning = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault() }; window.addEventListener("beforeunload", warning); return () => window.removeEventListener("beforeunload", warning) }, [dirty])
  const counts = useMemo(() => new Map(content?.categories.map(category => [category.id, content.items.filter(item => item.categoryId === category.id).length]) ?? []), [content])
  if (isLoading || !content || user?.role !== "super_admin_pc") return <div className="min-h-screen bg-background" />
  const patch = async () => { setBusy(true); setMessage(""); try { const response = await fetch("/api/gallery-content/manage", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(content) }); const payload: { content?: GalleryContent; error?: string } = await response.json(); if (!response.ok || !payload.content) throw new Error(payload.error); setContent(payload.content); setInitial(JSON.stringify(payload.content)); setMessage("Konten galeri berhasil disimpan.") } catch (error) { console.error("Gagal menyimpan galeri:", error); setMessage("Konten galeri belum dapat disimpan.") } finally { setBusy(false) } }
  const upload = async (file: File): Promise<GalleryAsset | null> => { const data = new FormData(); data.set("file", file); try { const response = await fetch("/api/gallery-content/upload", { method: "POST", body: data }); const payload: { asset?: GalleryAsset; error?: string } = await response.json(); if (!response.ok || !payload.asset) throw new Error(payload.error); return payload.asset } catch (error) { console.error("Gagal mengunggah aset galeri:", error); setMessage("Gambar belum dapat diunggah."); return null } }
  const categoryOptions = content.categories
  const visibleItems = content.items.filter(item => filter === "all" || item.categoryId === filter)
  const addItemFromUpload = async (file: File) => {
    const category = categoryOptions[0]
    if (!category) return
    setBusy(true)
    const image = await upload(file)
    if (image) setContent({ ...content, items: [...content.items, { id: `item-${Date.now()}`, title: "Dokumentasi Baru", description: "Deskripsi dokumentasi", categoryId: category.id, image, featured: false, visible: false, position: content.items.length }] })
    setBusy(false)
  }
  return <MemberLayout title="Galeri Publik" breadcrumb="Landing Page / Galeri"><div className="space-y-6 overflow-x-hidden pb-24">
    <section className="flex flex-col gap-4 rounded-3xl border bg-card p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold tracking-[.18em] text-[#15945b]">GALERI PUBLIK</p><h2 className="mt-2 text-3xl font-bold">Dokumentasi Editorial</h2><p className="mt-2 text-sm text-muted-foreground">Perubahan hanya diterbitkan setelah tombol Simpan dipilih.</p></div><div className="flex gap-2"><Button variant="outline" disabled={!dirty || busy} onClick={() => setContent(JSON.parse(initial))}><RotateCcw className="h-4 w-4" />Reset</Button><Button disabled={!dirty || busy} onClick={() => void patch()}><Save className="h-4 w-4" />{busy ? "Menyimpan..." : "Simpan"}</Button></div></section>
    {message && <p role="status" className="rounded-xl border bg-card p-4 text-sm">{message}</p>}
    <Card><CardHeader><CardTitle>Hero</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2"><Fields values={content.hero} onChange={(key, value) => setContent({ ...content, hero: { ...content.hero, [key]: value } })} fields={["eyebrow", "title", "highlightedText", "description"]} /><AssetInput label="Gambar Hero" asset={content.hero.image} upload={upload} onChange={image => setContent({ ...content, hero: { ...content.hero, image } })} /></CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Kategori</CardTitle><Button variant="outline" onClick={() => setContent({ ...content, categories: [...content.categories, { id: `kategori-${Date.now()}`, name: "Kategori Baru", description: "Deskripsi kategori", visible: true, position: content.categories.length }] })}><Plus className="h-4 w-4" />Tambah</Button></CardHeader><CardContent className="space-y-4">{content.categories.map((category, index) => <div key={category.id} className="grid gap-3 rounded-2xl border p-4 md:grid-cols-[1fr_2fr_auto]"><div><Label htmlFor={`category-${category.id}`}>Nama ({counts.get(category.id) ?? 0} item)</Label><Input id={`category-${category.id}`} value={category.name} onChange={event => setContent({ ...content, categories: content.categories.map(item => item.id === category.id ? { ...item, name: event.target.value } : item) })} /></div><div><Label htmlFor={`category-description-${category.id}`}>Deskripsi</Label><Input id={`category-description-${category.id}`} value={category.description} onChange={event => setContent({ ...content, categories: content.categories.map(item => item.id === category.id ? { ...item, description: event.target.value } : item) })} /></div><div className="flex items-end gap-1"><Button variant="outline" aria-label="Naikkan kategori" disabled={!index} onClick={() => setContent({ ...content, categories: move(content.categories, index, -1) })}><ArrowUp /></Button><Button variant="outline" aria-label="Turunkan kategori" disabled={index === content.categories.length - 1} onClick={() => setContent({ ...content, categories: move(content.categories, index, 1) })}><ArrowDown /></Button><Button variant="outline" aria-label="Ubah visibilitas kategori" onClick={() => setContent({ ...content, categories: content.categories.map(item => item.id === category.id ? { ...item, visible: !item.visible } : item) })}>{category.visible ? "Publik" : "Privat"}</Button><Button variant="destructive" aria-label="Hapus kategori" disabled={Boolean(counts.get(category.id))} onClick={() => confirm("Hapus kategori kosong ini?") && setContent({ ...content, categories: content.categories.filter(item => item.id !== category.id) })}><Trash2 /></Button></div></div>)}</CardContent></Card>
    <Card><CardHeader className="gap-4 sm:flex-row sm:items-center sm:justify-between"><CardTitle>Item Galeri</CardTitle><div className="flex flex-wrap gap-2"><select aria-label="Filter kategori" className="min-h-11 rounded-xl border bg-background px-3" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">Semua kategori</option>{categoryOptions.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label className={`inline-flex min-h-10 items-center gap-2 rounded-md border px-4 text-sm font-medium ${!categoryOptions.length || busy ? "cursor-not-allowed opacity-50" : "cursor-pointer"}`}>{busy ? "Mengunggah..." : "Unggah & Tambah"}<input type="file" accept="image/png,image/jpeg" className="sr-only" disabled={!categoryOptions.length || busy} onChange={event => { const file = event.target.files?.[0]; if (file) void addItemFromUpload(file); event.target.value = "" }} /></label></div></CardHeader><CardContent className="grid gap-5 xl:grid-cols-2">{visibleItems.map(item => <div key={item.id} className="space-y-4 rounded-2xl border p-4"><AssetInput label="Gambar" asset={item.image.fileSize ? item.image : undefined} upload={upload} onChange={image => image && setContent({ ...content, items: content.items.map(entry => entry.id === item.id ? { ...entry, image } : entry) })} /><Fields values={item} onChange={(key, value) => setContent({ ...content, items: content.items.map(entry => entry.id === item.id ? { ...entry, [key]: value } : entry) })} fields={["title", "description", "date", "location", "photographer", "altText"]} /><div><Label htmlFor={`item-category-${item.id}`}>Kategori</Label><select id={`item-category-${item.id}`} className="min-h-11 w-full rounded-xl border bg-background px-3" value={item.categoryId} onChange={event => setContent({ ...content, items: content.items.map(entry => entry.id === item.id ? { ...entry, categoryId: event.target.value } : entry) })}>{categoryOptions.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setContent({ ...content, items: content.items.map(entry => entry.id === item.id ? { ...entry, visible: !entry.visible, featured: entry.visible ? false : entry.featured } : entry) })}>{item.visible ? "Publik" : "Tersembunyi"}</Button><Button variant="outline" disabled={!item.visible} onClick={() => setContent({ ...content, items: content.items.map(entry => ({ ...entry, featured: entry.id === item.id ? !entry.featured : false })) })}>{item.featured ? "Unggulan" : "Jadikan Unggulan"}</Button><Button variant="destructive" onClick={() => confirm("Hapus item dari konten? File gambar tetap disimpan.") && setContent({ ...content, items: content.items.filter(entry => entry.id !== item.id) })}><Trash2 />Hapus</Button></div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Ajakan Tindakan</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2"><Fields values={content.callToAction} onChange={(key, value) => setContent({ ...content, callToAction: { ...content.callToAction, [key]: value } })} fields={["eyebrow", "title", "description", "primaryLabel", "primaryHref", "secondaryLabel", "secondaryHref"]} /><div className="space-y-4"><AssetInput label="Gambar Latar" asset={content.callToAction.backgroundImage} upload={upload} onChange={backgroundImage => setContent({ ...content, callToAction: { ...content.callToAction, backgroundImage } })} /><Button variant="outline" onClick={() => setContent({ ...content, callToAction: { ...content.callToAction, visible: !content.callToAction.visible } })}>{content.callToAction.visible ? "CTA Publik" : "CTA Tersembunyi"}</Button></div></CardContent></Card>
  </div></MemberLayout>
}
function Fields({ values, fields, onChange }: { values: Record<string, string | number | boolean | GalleryAsset | undefined>; fields: string[]; onChange: (key: string, value: string) => void }) { return <div className="grid gap-4">{fields.map(key => <div key={key}><Label htmlFor={`${key}-${String(values.id ?? "section")}`}>{labels[key] ?? key}</Label>{key === "description" ? <Textarea id={`${key}-${String(values.id ?? "section")}`} value={String(values[key] ?? "")} onChange={event => onChange(key, event.target.value)} /> : <Input id={`${key}-${String(values.id ?? "section")}`} type={key === "date" ? "date" : "text"} value={String(values[key] ?? "")} onChange={event => onChange(key, event.target.value)} />}</div>)}</div> }
const labels: Record<string, string> = { eyebrow: "Eyebrow", title: "Judul", highlightedText: "Teks Sorotan", description: "Deskripsi", date: "Tanggal", location: "Lokasi", photographer: "Fotografer", altText: "Teks Alternatif", primaryLabel: "Label Utama", primaryHref: "Tautan Utama", secondaryLabel: "Label Sekunder", secondaryHref: "Tautan Sekunder" }
function AssetInput({ label, asset, upload, onChange }: { label: string; asset?: GalleryAsset; upload: (file: File) => Promise<GalleryAsset | null>; onChange: (asset?: GalleryAsset) => void }) { const [busy, setBusy] = useState(false); return <div className="space-y-3"><Label>{label}</Label>{asset && <div className="relative aspect-video overflow-hidden rounded-xl border"><Image src={asset.path} alt="Pratinjau aset" fill className="object-cover" unoptimized /></div>}<label className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-xl border px-4 text-sm font-semibold"><ImagePlus className="h-4 w-4" />{busy ? "Mengunggah..." : "Unggah Gambar"}<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async event => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); onChange((await upload(file)) ?? asset); setBusy(false); event.target.value = "" }} /></label>{asset && <Button variant="outline" onClick={() => onChange(undefined)}>Hapus dari konten</Button>}</div> }
function move<T extends { position: number }>(items: T[], index: number, direction: -1 | 1): T[] { const next = [...items]; const target = index + direction; [next[index], next[target]] = [next[target], next[index]]; return next.map((item, position) => ({ ...item, position })) }
