"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import Image from "next/image"
import Link from "next/link"
import { Calendar, Camera, ChevronLeft, ChevronRight, MapPin, RefreshCcw } from "lucide-react"
import { PublicFooter } from "@/components/piindung/public-footer"
import { PublicNavbar } from "@/components/piindung/public-navbar"
import { PublicThemeDefault } from "@/components/piindung/public-theme-default"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import type { GalleryItem, PublicGalleryContent } from "@/lib/gallery-content"

const message = "Galeri belum dapat dimuat. Silakan coba kembali."
export default function GalleryPage() {
  const [content, setContent] = useState<PublicGalleryContent | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [category, setCategory] = useState("all")
  const [selected, setSelected] = useState<GalleryItem | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/gallery-content", { cache: "no-store" }); if (!response.ok) throw new Error(`Gallery HTTP ${response.status}`); const payload: { content?: PublicGalleryContent } = await response.json(); if (!payload.content) throw new Error("Gallery payload missing"); setContent(payload.content) } catch (cause) { console.error("Gagal memuat galeri publik:", cause); setError(message) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const items = useMemo(() => content?.items.filter(item => category === "all" || item.categoryId === category) ?? [], [category, content])
  const index = selected ? items.findIndex(item => item.id === selected.id) : -1
  useEffect(() => { if (!selected) return; const onKey = (event: KeyboardEvent) => { if (event.key === "ArrowLeft" && items.length) setSelected(items[(index - 1 + items.length) % items.length]); if (event.key === "ArrowRight" && items.length) setSelected(items[(index + 1) % items.length]) }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey) }, [index, items, selected])
  const featured = content?.items.find(item => item.featured)
  const cta = content?.callToAction
  return <div className="min-h-screen overflow-x-hidden bg-[#f7faf8] text-[#0b1f33] dark:bg-slate-950 dark:text-white"><PublicThemeDefault /><PublicNavbar /><main>
    {loading ? <div className="mx-auto max-w-7xl space-y-8 px-4 py-36 sm:px-6 lg:px-8"><div className="h-48 animate-pulse rounded-3xl bg-slate-200 motion-reduce:animate-none dark:bg-slate-800" /><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="aspect-[4/3] animate-pulse rounded-2xl bg-slate-200 motion-reduce:animate-none dark:bg-slate-800" />)}</div></div> : error ? <div className="mx-auto max-w-md px-4 py-36 text-center"><h1 className="text-2xl font-bold">Galeri Tidak Tersedia</h1><p className="mt-3 text-slate-600 dark:text-slate-300">{error}</p><button onClick={() => void load()} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#15945b] px-5 font-semibold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#15945b]"><RefreshCcw className="h-4 w-4" />Coba Lagi</button></div> : content ? <>
      <section className="relative px-4 pb-20 pt-36 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-bold tracking-[.18em] text-[#15945b]">{content.hero.eyebrow}</p><h1 className="mt-5 text-4xl font-bold tracking-tight sm:text-5xl">{content.hero.title} <span className="text-[#15945b]">{content.hero.highlightedText}</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">{content.hero.description}</p></div>{content.hero.image && <div className="relative aspect-[4/3] overflow-hidden rounded-3xl"><Image src={content.hero.image.path} alt={content.hero.highlightedText || content.hero.title} fill className="object-cover" priority unoptimized /></div>}</div></section>
      {featured && <section className="px-4 pb-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="mb-5 text-sm font-bold text-[#15945b]">DOKUMENTASI UNGGULAN</p><GalleryCard item={featured} onOpen={setSelected} featured /></div></section>}
      <section className="border-y border-[#dde7e2] bg-white px-4 py-16 dark:border-white/10 dark:bg-slate-900/50 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div role="group" aria-label="Filter kategori" className="mb-10 flex flex-wrap gap-3"><Filter active={category === "all"} onClick={() => setCategory("all")}>Semua</Filter>{content.categories.map(item => <Filter key={item.id} active={category === item.id} onClick={() => setCategory(item.id)}>{item.name}</Filter>)}</div>{items.length ? <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{items.map(item => <GalleryCard key={item.id} item={item} onOpen={setSelected} />)}</div> : <div className="py-20 text-center"><Camera className="mx-auto h-10 w-10 text-slate-400" /><h2 className="mt-4 text-xl font-bold">Belum Ada Dokumentasi Publik</h2><p className="mt-2 text-slate-600 dark:text-slate-300">Dokumentasi untuk kategori ini belum tersedia.</p></div>}</div></section>
      {cta?.visible && <section className="relative isolate px-4 py-20 text-white sm:px-6 lg:px-8" style={cta.backgroundImage ? { backgroundImage: `url('${cta.backgroundImage.path}')`, backgroundSize: "cover", backgroundPosition: "center" } : { backgroundColor: "#0f3460" }}><div className="absolute inset-0 -z-10 bg-[#071426]/70" /><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><p className="text-xs font-bold tracking-[.18em] text-emerald-200">{cta.eyebrow}</p><h2 className="mt-4 text-3xl font-bold">{cta.title}</h2><p className="mt-4 max-w-2xl text-white/80">{cta.description}</p></div><div className="flex flex-wrap gap-3"><Link className="inline-flex min-h-11 items-center rounded-xl bg-white px-5 font-semibold text-[#071426] focus-visible:ring-2 focus-visible:ring-white" href={cta.primaryHref}>{cta.primaryLabel}</Link>{cta.secondaryHref && <Link className="inline-flex min-h-11 items-center rounded-xl border border-white/60 px-5 font-semibold focus-visible:ring-2 focus-visible:ring-white" href={cta.secondaryHref}>{cta.secondaryLabel}</Link>}</div></div></section>}
    </> : null}
  </main><PublicFooter /><Dialog open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)}><DialogContent className="max-h-[90vh] overflow-y-auto p-0 sm:max-w-4xl"><DialogHeader className="sr-only"><DialogTitle>{selected?.title ?? "Pratinjau galeri"}</DialogTitle><DialogDescription>Detail dokumentasi galeri</DialogDescription></DialogHeader>{selected && <><div className="relative aspect-[4/3] bg-black"><Image src={selected.image.path} alt={selected.altText || selected.title} fill className="object-contain" unoptimized />{items.length > 1 && <><button aria-label="Dokumentasi sebelumnya" onClick={() => setSelected(items[(index - 1 + items.length) % items.length])} className="absolute left-3 top-1/2 flex h-11 w-11 -translate-y-1/2 items-center justify-center rounded-full bg-black/60 focus-visible:ring-2 focus-visible:ring-white"><ChevronLeft /></button><button aria-label="Dokumentasi berikutnya" onClick={() => setSelected(items[(index + 1) % items.length])} className="absolute right-3 top-1/2 flex h-11 w-11 -translate-y-1/2 items-center justify-center rounded-full bg-black/60 focus-visible:ring-2 focus-visible:ring-white"><ChevronRight /></button></>}</div><div className="space-y-3 p-6"><h2 className="text-2xl font-bold">{selected.title}</h2><Meta item={selected} /><p className="leading-7 text-zinc-300">{selected.description}</p>{selected.photographer && <p className="text-sm text-zinc-400">Fotografer: {selected.photographer}</p>}</div></>}</DialogContent></Dialog></div>
}
function Filter({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" aria-pressed={active} onClick={onClick} className={`min-h-11 rounded-full px-5 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#15945b] ${active ? "bg-[#15945b] text-white" : "border border-[#dde7e2] bg-white dark:border-white/10 dark:bg-slate-900"}`}>{children}</button> }
function GalleryCard({ item, onOpen, featured = false }: { item: GalleryItem; onOpen: (item: GalleryItem) => void; featured?: boolean }) { return <button type="button" onClick={() => onOpen(item)} className={`group overflow-hidden rounded-3xl border border-[#dde7e2] bg-white text-left shadow-sm transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#15945b] motion-reduce:transition-none dark:border-white/10 dark:bg-slate-900 ${featured ? "grid w-full lg:grid-cols-2" : ""}`}><div className="relative aspect-[4/3] overflow-hidden"><Image src={(item.thumbnail ?? item.image).path} alt={item.altText || item.title} fill sizes={featured ? "(max-width: 1024px) 100vw, 50vw" : "(max-width: 640px) 100vw, 33vw"} className="object-cover transition duration-500 group-hover:scale-[1.03] motion-reduce:transition-none motion-reduce:transform-none" unoptimized /></div><div className="p-6"><h2 className={featured ? "text-2xl font-bold" : "text-lg font-bold"}>{item.title}</h2><Meta item={item} /><p className="mt-3 line-clamp-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{item.description}</p></div></button> }
function Meta({ item }: { item: GalleryItem }) { return <div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-500 dark:text-slate-400">{item.date && <span className="inline-flex items-center gap-1"><Calendar className="h-3.5 w-3.5" />{new Date(`${item.date}T00:00:00`).toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" })}</span>}{item.location && <span className="inline-flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{item.location}</span>}</div> }
