"use client"

import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Play } from "lucide-react"
import { LandingReveal } from "@/components/piindung/landing-motion"

export function ArticlePreview() {
  return (
    <section id="artikel" className="scroll-mt-24 bg-[#f7faf8] py-20 dark:bg-[#07131f] sm:py-28" aria-labelledby="articles-heading"><LandingReveal className="mx-auto grid min-h-[570px] max-w-[1180px] overflow-hidden rounded-[32px] bg-[#08213b] text-white shadow-[0_28px_80px_rgba(0,0,0,.2)] lg:grid-cols-2"><div className="group relative min-h-[380px] overflow-hidden bg-[linear-gradient(140deg,#07965d,#08213b_70%)] lg:min-h-full"><Image src="/HERO%20PIINDUNG.png" alt="Pratinjau profil ekosistem PIINDUNG" fill className="object-cover opacity-45 mix-blend-luminosity transition-transform duration-700 ease-out group-hover:scale-[1.05]" sizes="(min-width:1024px) 50vw,100vw" /><div className="absolute inset-0 bg-[linear-gradient(90deg,transparent,rgba(8,33,59,.5))]" /><span className="pointer-events-none absolute left-1/2 top-1/2 h-[70px] w-[70px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-white/40 opacity-0 transition-opacity duration-300 group-hover:opacity-100 group-hover:motion-safe:animate-ping" aria-hidden="true" /><span className="absolute left-1/2 top-1/2 grid h-[70px] w-[70px] -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white text-[#07965d] shadow-xl transition-transform duration-300 group-hover:scale-[1.1]" aria-hidden="true"><Play className="ml-1 h-6 w-6 fill-current" /></span></div><div className="flex flex-col justify-center px-7 py-14 sm:px-12 lg:px-16"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-emerald-300">Wawasan dan Informasi</p><h2 id="articles-heading" className="mt-4 text-[clamp(2.25rem,3.8vw,3.45rem)] font-bold leading-[1.06] tracking-[-0.055em]">Digitalisasi bukan tentang sistem yang rumit.</h2><p className="mt-6 text-[15px] leading-8 text-white/68">PIINDUNG bukan sekadar aplikasi, tetapi ekosistem digital yang menghubungkan layanan, data, dan proses organisasi dalam satu kesatuan yang lebih tertib dan terintegrasi.</p><Link href="/produk" className="group mt-7 inline-flex w-fit items-center gap-2 text-sm font-semibold text-emerald-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-300">Lihat Produk PIINDUNG <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link><div className="mt-9 flex flex-wrap gap-2 text-[10px] font-semibold uppercase tracking-[.1em] text-white/60"><span className="rounded-full border border-white/15 px-3 py-1.5">Ekosistem Digital</span><span className="rounded-full border border-white/15 px-3 py-1.5">Transformasi Pelayanan</span></div></div></LandingReveal></section>
  )
}
