import { randomUUID } from "crypto"
import { cookies } from "next/headers"
import { NextResponse } from "next/server"
import { getPrismaClient } from "@/lib/prisma"
import { getRecord } from "@/lib/record-store-server"
import { AUTH_COOKIE_NAME, verifySessionToken } from "@/lib/session-token"
import { DEFAULT_DOWNLOAD_CONTENT, DOWNLOAD_CONTENT_KEY, DOWNLOAD_CONTENT_SCOPE, validateDownloadContent, type DownloadContent } from "@/lib/download-content"

const secret = process.env.AUTH_SECRET ?? "piindung-dev-auth-secret"
type Actor = { id: string; name: string; email: string | null; role: string }
export async function requireDownloadManager(): Promise<{ response: NextResponse } | { user: Actor }> { const token = (await cookies()).get(AUTH_COOKIE_NAME)?.value; const session = token ? await verifySessionToken(token, secret) : null; if (!session) return { response: NextResponse.json({ error: "Sesi tidak ditemukan." }, { status: 401 }) }; if (session.role !== "super_admin_pc") return { response: NextResponse.json({ error: "Akses tidak diizinkan." }, { status: 403 }) }; const users = await getPrismaClient().$queryRaw<Actor[]>`SELECT id, name, email, role FROM "User" WHERE id = ${session.sub} LIMIT 1`; const user = users[0]; if (user?.role !== "super_admin_pc") return { response: NextResponse.json({ error: "Akses tidak diizinkan." }, { status: 403 }) }; return { user } }
export async function readDownloadContent(): Promise<DownloadContent> { const record = await getRecord(DOWNLOAD_CONTENT_SCOPE, DOWNLOAD_CONTENT_KEY); if (!record) return DEFAULT_DOWNLOAD_CONTENT; try { return validateDownloadContent(record.data) } catch (error) { console.error("Invalid persisted download content:", error); return DEFAULT_DOWNLOAD_CONTENT } }
export async function updateDownloadContent(input: DownloadContent, actor: Actor) { const previous = await readDownloadContent(); const content = validateDownloadContent({ ...input, updatedAt: new Date().toISOString() }); const changedSections = (["hero", "categories", "items", "callToAction"] as const).filter(x => JSON.stringify(previous[x]) !== JSON.stringify(content[x])); return getPrismaClient().$transaction(async tx => { await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${DOWNLOAD_CONTENT_SCOPE + ":mutations"}))`; await tx.$executeRaw`INSERT INTO "AppRecord" ("id", "scope", "key", "data", "updatedAt") VALUES (${randomUUID()}, ${DOWNLOAD_CONTENT_SCOPE}, ${DOWNLOAD_CONTENT_KEY}, ${JSON.stringify(content)}::jsonb, NOW()) ON CONFLICT ("scope", "key") DO UPDATE SET "data" = EXCLUDED."data", "updatedAt" = NOW()`; const auditId = randomUUID(); const audit = { id: `log-${auditId}`, userName: actor.name, type: "Content", action: "download_content_updated", status: "Success", actorId: actor.id, actorEmail: actor.email, actorRole: actor.role, categoryCount: content.categories.length, visibleDocumentCount: content.items.filter(x => x.visible).length, hiddenDocumentCount: content.items.filter(x => !x.visible).length, featuredDocumentCount: content.items.filter(x => x.featured).length, uploadedCount: content.items.filter(x => x.sourceType === "uploaded").length, externalCount: content.items.filter(x => x.sourceType === "external").length, changedSections, timestamp: new Date().toISOString() }; await tx.$executeRaw`INSERT INTO "AppRecord" ("id", "scope", "key", "data", "updatedAt") VALUES (${randomUUID()}, 'activity-log', ${`download-content-updated-${auditId}`}, ${JSON.stringify(audit)}::jsonb, NOW())`; return content }) }
export async function auditDownloadUpload(actor: Actor, fileType: string, fileSize: number) { const auditId = randomUUID(); const audit = { id: `log-${auditId}`, userName: actor.name, type: "Content", action: "download_asset_uploaded", status: "Success", actorId: actor.id, actorEmail: actor.email, actorRole: actor.role, fileType, fileSize, timestamp: new Date().toISOString() }; await getPrismaClient().$executeRaw`INSERT INTO "AppRecord" ("id", "scope", "key", "data", "updatedAt") VALUES (${randomUUID()}, 'activity-log', ${`download-asset-uploaded-${auditId}`}, ${JSON.stringify(audit)}::jsonb, NOW())` }
