import { randomUUID } from "crypto"
import { cookies } from "next/headers"
import { NextResponse } from "next/server"
import { getPrismaClient } from "@/lib/prisma"
import { getRecord } from "@/lib/record-store-server"
import { AUTH_COOKIE_NAME, verifySessionToken } from "@/lib/session-token"
import { DEFAULT_GALLERY_CONTENT, GALLERY_CONTENT_KEY, GALLERY_CONTENT_SCOPE, validateGalleryContent, type GalleryContent } from "@/lib/gallery-content"

const secret = process.env.AUTH_SECRET ?? "piindung-dev-auth-secret"
type Actor = { id: string; name: string; email: string | null; role: string }
export async function readGalleryContent(): Promise<GalleryContent> { const record = await getRecord(GALLERY_CONTENT_SCOPE, GALLERY_CONTENT_KEY); if (!record) return DEFAULT_GALLERY_CONTENT; try { return validateGalleryContent(record.data) } catch (error) { console.error("Invalid persisted gallery content:", error); return DEFAULT_GALLERY_CONTENT } }
export async function requireGalleryManager(): Promise<{ response: NextResponse } | { user: Actor }> { const token = (await cookies()).get(AUTH_COOKIE_NAME)?.value; const session = token ? await verifySessionToken(token, secret) : null; if (!session) return { response: NextResponse.json({ error: "Sesi tidak ditemukan." }, { status: 401 }) }; if (session.role !== "super_admin_pc") return { response: NextResponse.json({ error: "Akses tidak diizinkan." }, { status: 403 }) }; const users = await getPrismaClient().$queryRaw<Actor[]>`SELECT id, name, email, role FROM "User" WHERE id = ${session.sub} LIMIT 1`; const user = users[0]; if (user?.role !== "super_admin_pc") return { response: NextResponse.json({ error: "Akses tidak diizinkan." }, { status: 403 }) }; return { user } }
export async function updateGalleryContent(input: GalleryContent, actor: Actor) { const previous = await readGalleryContent(); const content = validateGalleryContent({ ...input, updatedAt: new Date().toISOString() }); const sections = (["hero", "categories", "items", "callToAction"] as const).filter(section => JSON.stringify(previous[section]) !== JSON.stringify(content[section])); return getPrismaClient().$transaction(async tx => { await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${GALLERY_CONTENT_SCOPE + ":mutations"}))`; await tx.$executeRaw`INSERT INTO "AppRecord" ("id", "scope", "key", "data", "updatedAt") VALUES (${randomUUID()}, ${GALLERY_CONTENT_SCOPE}, ${GALLERY_CONTENT_KEY}, ${JSON.stringify(content)}::jsonb, NOW()) ON CONFLICT ("scope", "key") DO UPDATE SET "data" = EXCLUDED."data", "updatedAt" = NOW()`; const auditId = randomUUID(); const audit = { id: `log-${auditId}`, userName: actor.name, type: "Content", action: "gallery_content_updated", status: "Success", actorId: actor.id, actorEmail: actor.email, actorRole: actor.role, categoryCount: content.categories.length, visibleItemCount: content.items.filter(item => item.visible).length, hiddenItemCount: content.items.filter(item => !item.visible).length, featuredItemCount: content.items.filter(item => item.featured).length, sections, timestamp: new Date().toISOString() }; await tx.$executeRaw`INSERT INTO "AppRecord" ("id", "scope", "key", "data", "updatedAt") VALUES (${randomUUID()}, 'activity-log', ${`gallery-content-updated-${auditId}`}, ${JSON.stringify(audit)}::jsonb, NOW())`; return content }) }
