export const gorutKecamatanOptions = [
  "Garut Kota",
  "Karangpawitan",
  "Wanaraja",
  "Tarogong Kaler",
  "Tarogong Kidul",
  "Samarang",
  "Bayongbong",
  "Cilawu",
  "Cisurupan",
  "Cigedug",
  "Sukaresmi",
  "Cikajang",
  "Banjarwangi",
  "Singajaya",
  "Mekarmukti",
  "Peundeuy",
  "Pakenjeng",
  "Pamulihan",
  "Cisewu",
  "Caringin",
  "Talegong",
  "Bungbulang",
  "Mekarwangi",
  "Cibalong",
  "Pameungpeuk",
  "Cikelet",
  "Cisompet",
  "Cihurip",
  "Cikandang",
  "Cibatu",
  "Kersamanah",
  "Malangbong",
  "Leles",
  "Leuwigoong",
  "Kadungora",
  "Selaawi",
  "Balubur Limbangan",
  "Blubur Limbangan",
  "Pasirwangi",
  "Sucinaraja",
  "Pangatikan",
  "Banyuresmi",
] as const

export type GorutKecamatanName = (typeof gorutKecamatanOptions)[number]
