export const IMPACT_CONTENT_SCOPE = "impact-content"
export const IMPACT_CONTENT_KEY = "main"
export const IMPACT_ICON_KEYS = ["users", "hand-heart", "building", "map-pin", "package", "chart", "calendar", "shield"] as const
export type ImpactIconKey = typeof IMPACT_ICON_KEYS[number]
export type ImpactAsset = { path: string; width: number; height: number; mimeType: "image/png" | "image/jpeg" | "image/webp"; fileSize: number; updatedAt: string }
export type Statistic = { id: string; label: string; value: string; prefix: string; suffix: string; description: string; iconKey: ImpactIconKey; visible: boolean; position: number }
export type Achievement = { id: string; title: string; description: string; year?: string; image?: ImpactAsset; link?: string; visible: boolean; position: number }
export type ImpactStory = { id: string; title: string; excerpt: string; body: string; image?: ImpactAsset; location?: string; programId?: string; status: "draft" | "published"; featured: boolean; position: number; publishedAt?: string }
export type TimelineItem = { id: string; yearLabel: string; title: string; description: string; visible: boolean; position: number }
export type ImpactCaseStudyItem = { id: string; step: string; title: string; description: string; image?: ImpactAsset; summaryItems?: { id: string; iconKey: string; label: string; value: string; status?: string; visible: boolean; position: number }[]; visible: boolean; position: number }
export type ImpactTestimonialItem = { id: string; name: string; role: string; quote: string; rating: number; avatar?: ImpactAsset; visible: boolean; position: number }
export type ImpactStatSection = { eyebrow: string; title: string; description: string; items: Statistic[] }
export type ImpactCaseStudySection = { eyebrow: string; title: string; description: string; items: ImpactCaseStudyItem[] }
export type ImpactTestimonialSection = { eyebrow: string; title: string; description: string; items: ImpactTestimonialItem[] }
export type ImpactContent = { hero: { eyebrow: string; title: string; highlightedText: string; description: string; image?: ImpactAsset }; statistics: Statistic[]; achievements: Achievement[]; stories: ImpactStory[]; timeline: TimelineItem[]; callToAction: { eyebrow: string; title: string; description: string; primaryLabel: string; primaryHref: string; secondaryLabel: string; secondaryHref: string; backgroundImage?: ImpactAsset; visible: boolean }; impactStats: ImpactStatSection; caseStudies: ImpactCaseStudySection; testimonials: ImpactTestimonialSection; updatedAt: string }

const epoch = new Date(0).toISOString()
export const DEFAULT_IMPACT_CONTENT: ImpactContent = {
  hero: { eyebrow: "DAMPAK DIGITALISASI", title: "Teknologi yang Membantu", highlightedText: "Pelayanan Lebih Tertib", description: "PIINDUNG dikembangkan untuk membantu pengurus bekerja lebih terarah, mengurangi proses berulang, menyatukan informasi, dan menyediakan data yang lebih mudah dipahami serta dipantau." },
  statistics: [], achievements: [], stories: [],
  timeline: [
    { id: "data-masuk", yearLabel: "Tahap 1", title: "Data Masuk", description: "Informasi dihimpun dalam alur yang terhubung.", visible: true, position: 0 },
    { id: "pemeriksaan", yearLabel: "Tahap 2", title: "Pemeriksaan", description: "Informasi diperiksa sebelum dikelola.", visible: true, position: 1 },
    { id: "pengelolaan", yearLabel: "Tahap 3", title: "Pengelolaan", description: "Data dikelola secara lebih terstruktur.", visible: true, position: 2 },
    { id: "pelayanan", yearLabel: "Tahap 4", title: "Pelayanan", description: "Informasi mendukung pelayanan organisasi.", visible: true, position: 3 },
    { id: "pelaporan", yearLabel: "Tahap 5", title: "Pelaporan", description: "Informasi dirangkum menjadi laporan yang tertata.", visible: true, position: 4 },
  ],
  callToAction: { eyebrow: "PIINDUNG UNTUK ORGANISASI", title: "Bersama Membangun Pelayanan yang Lebih Terhubung", description: "Pelajari bagaimana ekosistem PIINDUNG membantu mendukung pelayanan dan tata kelola NU Care–LAZISNU Garut.", primaryLabel: "Lihat Produk", primaryHref: "/produk", secondaryLabel: "Pusat Bantuan", secondaryHref: "/bantuan", visible: true },
  impactStats: { eyebrow: "Gambaran Dampak Sistem", title: "Skala ekosistem yang terus tumbuh", description: "Angka bersifat demonstratif untuk menggambarkan skala ekosistem PIINDUNG dan akan diperbarui secara berkala setelah tersambung penuh dengan data operasional resmi.", items: [
    { id: "munfiq-terdata", label: "Munfiq Terdata", value: "3.482", prefix: "", suffix: "+", description: "Data munfiq tercatat dalam ekosistem.", iconKey: "users", visible: true, position: 0 },
    { id: "plpk-terhubung", label: "PLPK Terhubung", value: "38", prefix: "", suffix: "+", description: "PLPK terhubung dalam alur pelayanan.", iconKey: "building", visible: true, position: 1 },
    { id: "transaksi-tercatat", label: "Transaksi Tercatat", value: "12.640", prefix: "", suffix: "+", description: "Transaksi tercatat secara terstruktur.", iconKey: "chart", visible: true, position: 2 },
    { id: "wilayah-terpantau", label: "Wilayah Terpantau", value: "42", prefix: "", suffix: " kecamatan", description: "Wilayah layanan dapat dipantau.", iconKey: "map-pin", visible: true, position: 3 },
  ] },
  caseStudies: { eyebrow: "Studi Kasus", title: "Bagaimana PIINDUNG bekerja pada setiap tahap pelayanan", description: "Empat gambaran alur kerja yang menunjukkan bagaimana data bergerak dari pencatatan hingga pelaporan.", items: [
    { id: "penghimpunan-transaksi", step: "Tahap 1", title: "Penghimpunan yang Lebih Terdata", description: "PIINDUNG membantu pencatatan transaksi penghimpunan secara lebih terstruktur agar data dari petugas lapangan hingga pengurus dapat dipantau dalam satu alur.", summaryItems: [{ id: "munfiq", iconKey: "users", label: "Munfiq", value: "3.482+", visible: true, position: 0 }, { id: "penghimpunan", iconKey: "chart", label: "Penghimpunan", value: "Tercatat", visible: true, position: 1 }, { id: "penyaluran", iconKey: "shield", label: "Penyaluran", value: "Terverifikasi", visible: true, position: 2 }, { id: "pelaporan", iconKey: "calendar", label: "Pelaporan", value: "Tersusun", visible: true, position: 3 }], visible: true, position: 0 },
    { id: "pendataan-munfiq", step: "Tahap 2", title: "Data Munfiq Lebih Terpusat", description: "Data munfiq yang sebelumnya tersebar dapat dicatat dan dikelola secara terstruktur berdasarkan wilayah, petugas, serta status pelayanan.", summaryItems: [{ id: "munfiq", iconKey: "users", label: "Munfiq", value: "3.482+", visible: true, position: 0 }, { id: "penghimpunan", iconKey: "chart", label: "Penghimpunan", value: "Tercatat", visible: true, position: 1 }, { id: "penyaluran", iconKey: "shield", label: "Penyaluran", value: "Terverifikasi", visible: true, position: 2 }, { id: "pelaporan", iconKey: "calendar", label: "Pelaporan", value: "Tersusun", visible: true, position: 3 }], visible: true, position: 1 },
    { id: "monitoring-validasi", step: "Tahap 3", title: "Monitoring Setoran Lebih Mudah", description: "Pengurus dapat mengikuti status setoran dan proses validasi secara lebih jelas, mulai dari pencatatan hingga pemeriksaan.", summaryItems: [{ id: "munfiq", iconKey: "users", label: "Munfiq", value: "3.482+", visible: true, position: 0 }, { id: "penghimpunan", iconKey: "chart", label: "Penghimpunan", value: "Tercatat", visible: true, position: 1 }, { id: "penyaluran", iconKey: "shield", label: "Penyaluran", value: "Terverifikasi", visible: true, position: 2 }, { id: "pelaporan", iconKey: "calendar", label: "Pelaporan", value: "Tersusun", visible: true, position: 3 }], visible: true, position: 2 },
    { id: "pelaporan", step: "Tahap 4", title: "Laporan Lebih Rapi dan Akuntabel", description: "Data yang telah tercatat dapat dirangkum menjadi laporan yang lebih konsisten untuk mendukung evaluasi dan pengambilan keputusan.", summaryItems: [{ id: "munfiq", iconKey: "users", label: "Munfiq", value: "3.482+", visible: true, position: 0 }, { id: "penghimpunan", iconKey: "chart", label: "Penghimpunan", value: "Tercatat", visible: true, position: 1 }, { id: "penyaluran", iconKey: "shield", label: "Penyaluran", value: "Terverifikasi", visible: true, position: 2 }, { id: "pelaporan", iconKey: "calendar", label: "Pelaporan", value: "Tersusun", visible: true, position: 3 }], visible: true, position: 3 },
  ] },
  testimonials: { eyebrow: "Apa Kata Mereka?", title: "Suara pengurus dan mitra layanan", description: "Kesan dari pengurus yang telah menggunakan ekosistem PIINDUNG.", items: [] },
  updatedAt: epoch,
}

const control = /[\u0000-\u001f\u007f]/
function text(value: unknown, name: string, max: number, optional = false) { if (optional && (value === undefined || value === "")) return undefined; if (typeof value !== "string" || !value.trim() || value.length > max || control.test(value) || /<[^>]*>/.test(value)) throw new Error(`${name} tidak valid.`); return value.trim() }
function position(value: unknown) { if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0 || value > 10000) throw new Error("Posisi tidak valid."); return value }
function id(value: unknown) { const result = text(value, "ID", 80); if (!/^[a-z0-9][a-z0-9_-]*$/.test(result!)) throw new Error("ID tidak valid."); return result! }
function link(value: unknown, name: string, optional = false) { const result = text(value, name, 300, optional); if (!result) return undefined; if (result.startsWith("/") && !result.startsWith("//") && !result.includes("..") && !result.includes("\\")) return result; try { const url = new URL(result); if (url.protocol === "https:") return url.toString() } catch {} throw new Error(`${name} tidak aman.`) }
function asset(value: unknown, name: string): ImpactAsset | undefined { if (value === undefined) return undefined; if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${name} tidak valid.`); const a = value as Record<string, unknown>; const path = link(a.path, `${name} path`); if (!path?.startsWith("/")) throw new Error(`${name} harus berupa aset internal.`); if (a.mimeType !== "image/png" && a.mimeType !== "image/jpeg" && a.mimeType !== "image/webp") throw new Error(`${name} MIME tidak valid.`); if (typeof a.width !== "number" || !Number.isSafeInteger(a.width) || a.width < 1 || a.width > 10000 || typeof a.height !== "number" || !Number.isSafeInteger(a.height) || a.height < 1 || a.height > 10000 || typeof a.fileSize !== "number" || !Number.isSafeInteger(a.fileSize) || a.fileSize < 0 || a.fileSize > 10 * 1024 * 1024) throw new Error(`${name} metadata tidak valid.`); return { path, width: a.width, height: a.height, mimeType: a.mimeType, fileSize: a.fileSize, updatedAt: text(a.updatedAt, `${name} updatedAt`, 40)! } }
function unique(items: { id: string }[], name: string) { if (new Set(items.map(item => item.id)).size !== items.length) throw new Error(`ID ${name} harus unik.`) }

function statistic(raw: unknown, index: number): Statistic { const x = raw as Record<string, unknown>; const value = text(x.value, `Nilai statistik ${index + 1}`, 40)!; if (!/^[\d.,+\-\s%/A-Za-z]+$/.test(value)) throw new Error("Nilai statistik tidak valid."); if (!IMPACT_ICON_KEYS.includes(x.iconKey as ImpactIconKey)) throw new Error("Ikon statistik tidak valid."); return { id: id(x.id), label: text(x.label, "Label statistik", 100)!, value, prefix: text(x.prefix, "Prefix", 20, true) ?? "", suffix: text(x.suffix, "Suffix", 20, true) ?? "", description: text(x.description, "Deskripsi statistik", 240)!, iconKey: x.iconKey as ImpactIconKey, visible: x.visible === true, position: position(x.position) } }
function section(raw: unknown) { const x = raw as Record<string, unknown>; if (!x || typeof x !== "object" || Array.isArray(x)) throw new Error("Section tidak valid."); return { eyebrow: text(x.eyebrow, "Eyebrow", 200)!, title: text(x.title, "Judul", 300)!, description: text(x.description, "Deskripsi", 800)! } }
const sortItems = <T extends { position: number }>(items: T[]) => [...items].sort((a, b) => a.position - b.position)

export function validateImpactContent(value: unknown): ImpactContent {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Payload dampak tidak valid.")
  const v = value as Record<string, unknown>
  const h = v.hero as Record<string, unknown>
  const c = v.callToAction as Record<string, unknown>
  if (!h || !c || !Array.isArray(v.statistics) || !Array.isArray(v.achievements) || !Array.isArray(v.stories) || !Array.isArray(v.timeline)) throw new Error("Struktur dampak tidak valid.")
  if (v.statistics.length > 20 || v.achievements.length > 50 || v.stories.length > 100 || v.timeline.length > 50) throw new Error("Struktur dampak tidak valid.")

  const statistics = v.statistics.map(statistic)
  const achievements = v.achievements.map(raw => { const x = raw as Record<string, unknown>; return { id: id(x.id), title: text(x.title, "Judul pencapaian", 140)!, description: text(x.description, "Deskripsi pencapaian", 500)!, year: text(x.year, "Tahun", 30, true), image: asset(x.image, "Gambar pencapaian"), link: link(x.link, "Tautan pencapaian", true), visible: x.visible === true, position: position(x.position) } })
  const stories: ImpactStory[] = v.stories.map(raw => { const x = raw as Record<string, unknown>; if (x.status !== "draft" && x.status !== "published") throw new Error("Status cerita tidak valid."); const publishedAt = text(x.publishedAt, "Tanggal publikasi cerita", 40, true); return { id: id(x.id), title: text(x.title, "Judul cerita", 200)!, excerpt: text(x.excerpt, "Ringkasan cerita", 500)!, body: text(x.body, "Isi cerita", 5000, true) ?? "", image: asset(x.image, "Foto cerita"), location: text(x.location, "Lokasi", 100, true), programId: text(x.programId, "ID program", 80, true), status: x.status, featured: x.featured === true, position: position(x.position), ...(publishedAt ? { publishedAt } : {}) } })
  const timeline = v.timeline.map(raw => { const x = raw as Record<string, unknown>; return { id: id(x.id), yearLabel: text(x.yearLabel, "Label timeline", 80)!, title: text(x.title, "Judul timeline", 200)!, description: text(x.description, "Deskripsi timeline", 800)!, visible: x.visible === true, position: position(x.position) } })
  unique(statistics, "statistik"); unique(achievements, "pencapaian"); unique(stories, "cerita"); unique(timeline, "timeline")

  const rawStats = v.impactStats as Record<string, unknown> | undefined
  const rawCases = v.caseStudies as Record<string, unknown> | undefined
  const rawTestimonials = v.testimonials as Record<string, unknown> | undefined
  const impactStats = rawStats ? { ...section(rawStats), items: Array.isArray(rawStats.items) ? rawStats.items.map(statistic) : [] } : DEFAULT_IMPACT_CONTENT.impactStats
  const caseStudies = rawCases ? { ...section(rawCases), items: Array.isArray(rawCases.items) ? rawCases.items.map(raw => { const x = raw as Record<string, unknown>; const summaryItems = Array.isArray(x.summaryItems) ? x.summaryItems.slice(0, 4).map(rawItem => { const item = rawItem as Record<string, unknown>; return { id: id(item.id), iconKey: text(item.iconKey, "Icon ringkasan", 100)!, label: text(item.label, "Label ringkasan", 100)!, value: text(item.value, "Nilai ringkasan", 100)!, status: text(item.status, "Status ringkasan", 100, true), visible: item.visible === true, position: position(item.position) } }) : []; unique(summaryItems, `ringkasan studi kasus ${id(x.id)}`); return { id: id(x.id), step: text(x.step, "Step studi kasus", 100)!, title: text(x.title, "Judul studi kasus", 200)!, description: text(x.description, "Deskripsi studi kasus", 1000)!, image: asset(x.image, "Gambar studi kasus"), summaryItems: sortItems(summaryItems), visible: x.visible === true, position: position(x.position) } }) : [] } : DEFAULT_IMPACT_CONTENT.caseStudies
  const testimonials = rawTestimonials ? { ...section(rawTestimonials), items: Array.isArray(rawTestimonials.items) ? rawTestimonials.items.map(raw => { const x = raw as Record<string, unknown>; const rating = typeof x.rating === "number" && Number.isSafeInteger(x.rating) && x.rating >= 1 && x.rating <= 5 ? x.rating : 5; return { id: id(x.id), name: text(x.name, "Nama testimoni", 100)!, role: text(x.role, "Role testimoni", 250)!, quote: text(x.quote, "Quote testimoni", 1000)!, rating, avatar: asset(x.avatar, "Avatar testimoni"), visible: x.visible === true, position: position(x.position) } }) : [] } : DEFAULT_IMPACT_CONTENT.testimonials
  unique(impactStats.items, "statistik ekosistem"); unique(caseStudies.items, "studi kasus"); unique(testimonials.items, "testimoni")

  return { hero: { eyebrow: text(h.eyebrow, "Eyebrow hero", 200)!, title: text(h.title, "Judul hero", 300)!, highlightedText: text(h.highlightedText, "Sorotan hero", 200, true) ?? "", description: text(h.description, "Deskripsi hero", 800)!, ...(h.image ? { image: asset(h.image, "Gambar hero") } : {}) }, statistics: sortItems(statistics), achievements: sortItems(achievements), stories: sortItems(stories), timeline: sortItems(timeline), callToAction: { eyebrow: text(c.eyebrow, "Eyebrow CTA", 200)!, title: text(c.title, "Judul CTA", 300)!, description: text(c.description, "Deskripsi CTA", 800)!, primaryLabel: text(c.primaryLabel, "Label tombol utama", 100)!, primaryHref: link(c.primaryHref, "Tautan utama")!, secondaryLabel: text(c.secondaryLabel, "Label tombol kedua", 100)!, secondaryHref: link(c.secondaryHref, "Tautan kedua")!, ...(c.backgroundImage ? { backgroundImage: asset(c.backgroundImage, "Gambar latar CTA") } : {}), visible: c.visible !== false }, impactStats: { ...impactStats, items: sortItems(impactStats.items) }, caseStudies: { ...caseStudies, items: sortItems(caseStudies.items) }, testimonials: { ...testimonials, items: sortItems(testimonials.items) }, updatedAt: typeof v.updatedAt === "string" ? v.updatedAt : new Date().toISOString() }
}

export function toPublicImpactContent(value: ImpactContent) { const content = validateImpactContent(value); return { hero: content.hero, statistics: content.statistics.filter(x => x.visible), achievements: content.achievements.filter(x => x.visible), stories: content.stories.filter(x => x.status === "published").map(story => { const result: Partial<ImpactStory> = { ...story }; delete result.status; return result }), timeline: content.timeline.filter(x => x.visible), callToAction: content.callToAction, impactStats: { ...content.impactStats, items: content.impactStats.items.filter(x => x.visible) }, caseStudies: { ...content.caseStudies, items: content.caseStudies.items.filter(x => x.visible) }, testimonials: { ...content.testimonials, items: content.testimonials.items.filter(x => x.visible) } } }
