import { randomUUID } from "crypto"
import { cookies } from "next/headers"
import { NextResponse } from "next/server"
import { getPrismaClient } from "@/lib/prisma"
import { getRecord } from "@/lib/record-store-server"
import { AUTH_COOKIE_NAME, verifySessionToken } from "@/lib/session-token"
import { DEFAULT_IMPACT_CONTENT, IMPACT_CONTENT_KEY, IMPACT_CONTENT_SCOPE, validateImpactContent, type ImpactContent } from "@/lib/impact-content"

const secret = process.env.AUTH_SECRET ?? "piindung-dev-auth-secret"
type Actor = { id: string; name: string; email: string | null; role: string }
export async function readImpactContent() { const record = await getRecord(IMPACT_CONTENT_SCOPE, IMPACT_CONTENT_KEY); if (!record) return DEFAULT_IMPACT_CONTENT; try { return validateImpactContent(record.data) } catch { return DEFAULT_IMPACT_CONTENT } }
export async function requireImpactManager() { const token = (await cookies()).get(AUTH_COOKIE_NAME)?.value; const session = token ? await verifySessionToken(token, secret) : null; if (!session) return { response: NextResponse.json({ error: "Sesi tidak ditemukan." }, { status: 401 }) }; if (session.role !== "super_admin_pc") return { response: NextResponse.json({ error: "Akses tidak diizinkan." }, { status: 403 }) }; const users = await getPrismaClient().$queryRaw<Actor[]>`SELECT id, name, email, role FROM "User" WHERE id = ${session.sub} LIMIT 1`; const user = users[0]; if (user?.role !== "super_admin_pc") return { response: NextResponse.json({ error: "Akses tidak diizinkan." }, { status: 403 }) }; return { user } }
export async function updateImpactContent(input: ImpactContent, actor: Actor) { const previous = await readImpactContent(); const content = validateImpactContent({ ...input, updatedAt: new Date().toISOString() }); const sections = (["hero", "statistics", "achievements", "stories", "timeline", "callToAction"] as const).filter(section => JSON.stringify(previous[section]) !== JSON.stringify(content[section])); return getPrismaClient().$transaction(async tx => { await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${IMPACT_CONTENT_SCOPE + ":mutations"}))`; await tx.$executeRaw`INSERT INTO "AppRecord" ("id", "scope", "key", "data", "updatedAt") VALUES (${randomUUID()}, ${IMPACT_CONTENT_SCOPE}, ${IMPACT_CONTENT_KEY}, ${JSON.stringify(content)}::jsonb, NOW()) ON CONFLICT ("scope", "key") DO UPDATE SET "data" = EXCLUDED."data", "updatedAt" = NOW()`; const auditId = randomUUID(); const audit = { id: `log-${auditId}`, userName: actor.name, type: "Content", action: "impact_content_updated", status: "Success", actorId: actor.id, actorEmail: actor.email, actorRole: actor.role, statisticCount: content.statistics.length, achievementCount: content.achievements.length, publishedStoryCount: content.stories.filter(x => x.status === "published").length, draftStoryCount: content.stories.filter(x => x.status === "draft").length, timelineCount: content.timeline.length, sections, timestamp: new Date().toISOString() }; await tx.$executeRaw`INSERT INTO "AppRecord" ("id", "scope", "key", "data", "updatedAt") VALUES (${randomUUID()}, 'activity-log', ${`impact-content-updated-${auditId}`}, ${JSON.stringify(audit)}::jsonb, NOW())`; return content }) }
