import { randomUUID } from "crypto"
import { cookies } from "next/headers"
import { NextResponse } from "next/server"
import { getPrismaClient } from "@/lib/prisma"
import { getRecord, listRecords } from "@/lib/record-store-server"
import { AUTH_COOKIE_NAME, verifySessionToken } from "@/lib/session-token"
import { countBrandingAssets, DEFAULT_SITE_BRANDING, SITE_BRANDING_KEY, SITE_BRANDING_SCOPE, validateSiteBranding, type BrandAsset, type SiteBranding } from "@/lib/site-branding"

const SECRET = process.env.AUTH_SECRET ?? "piindung-dev-auth-secret"
type BrandingActor = { id: string; name: string; email: string | null; role: string }

export async function readSiteBranding() { const record = await getRecord(SITE_BRANDING_SCOPE, SITE_BRANDING_KEY); if (!record) return DEFAULT_SITE_BRANDING; try { return validateSiteBranding(record.data) } catch { return DEFAULT_SITE_BRANDING } }
export async function requireBrandingManager() { const token = (await cookies()).get(AUTH_COOKIE_NAME)?.value; const session = token ? await verifySessionToken(token, SECRET) : null; if (!session) return { response: NextResponse.json({ error: "Sesi tidak ditemukan." }, { status: 401 }) }; if (session.role !== "super_admin_pc") return { response: NextResponse.json({ error: "Akses tidak diizinkan." }, { status: 403 }) }; const users = await getPrismaClient().$queryRaw<BrandingActor[]>`SELECT id, name, email, role FROM "User" WHERE id = ${session.sub} LIMIT 1`; const user = users[0]; if (user?.role !== "super_admin_pc") return { response: NextResponse.json({ error: "Akses tidak diizinkan." }, { status: 403 }) }; return { user } }

function changedSections(before: SiteBranding, after: SiteBranding) { return (["identity", "logos", "icons", "socialPreview", "fallbackMedia"] as const).filter(section => JSON.stringify(before[section]) !== JSON.stringify(after[section])) }
export async function updateSiteBranding(input: SiteBranding, actor: BrandingActor) { const current = await readSiteBranding(); const branding = validateSiteBranding({ ...input, updatedAt: new Date().toISOString() }); const sections = changedSections(current, branding); const changes = { navbar: current.logos.navbarLight.path !== branding.logos.navbarLight.path || current.logos.navbarDark.path !== branding.logos.navbarDark.path, footer: current.logos.footerLight.path !== branding.logos.footerLight.path || current.logos.footerDark.path !== branding.logos.footerDark.path, favicon: current.icons.favicon.path !== branding.icons.favicon.path, og: current.socialPreview.defaultOgImage.path !== branding.socialPreview.defaultOgImage.path }; return getPrismaClient().$transaction(async tx => { await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${SITE_BRANDING_SCOPE + ":mutations"}))`; await tx.$executeRaw`INSERT INTO "AppRecord" ("id", "scope", "key", "data", "updatedAt") VALUES (${randomUUID()}, ${SITE_BRANDING_SCOPE}, ${SITE_BRANDING_KEY}, ${JSON.stringify(branding)}::jsonb, NOW()) ON CONFLICT ("scope", "key") DO UPDATE SET "data" = EXCLUDED."data", "updatedAt" = NOW()`; const id = randomUUID(); const audit = { id: `log-${id}`, userName: actor.name, type: "System", action: "site_branding_updated", status: "Success", actorId: actor.id, actorEmail: actor.email, actorRole: actor.role, sections, activeAssetReferences: countBrandingAssets(branding), changes, timestamp: new Date().toISOString() }; await tx.$executeRaw`INSERT INTO "AppRecord" ("id", "scope", "key", "data", "updatedAt") VALUES (${randomUUID()}, 'activity-log', ${`site-branding-updated-${id}`}, ${JSON.stringify(audit)}::jsonb, NOW())`; return branding }) }

function legacyAsset(value: unknown): BrandAsset | null { if (!value || typeof value !== "string" || !value.startsWith("/") || value.includes("..") || value.includes("\\")) return null; return { path: value, width: 200, height: 50, mimeType: "image/png", fileSize: 0, updatedAt: new Date().toISOString() } }
export async function previewLegacyMedia() { const records = await listRecords("media-library"); const imported: Array<{ key: string; asset: BrandAsset }> = []; const invalid: string[] = []; for (const record of records) { const data = record.data as Record<string, unknown>; if (data.type !== "logo") continue; const asset = legacyAsset(data.url); if (asset) imported.push({ key: record.key, asset }); else invalid.push(record.key) } return { imported, skipped: records.length - imported.length - invalid.length, invalid, missing: [], total: records.length } }
export async function migrateLegacyMedia(actor: BrandingActor) { const existing = await getRecord(SITE_BRANDING_SCOPE, SITE_BRANDING_KEY); if (existing) return { migrated: false, branding: validateSiteBranding(existing.data), preview: await previewLegacyMedia() }; const preview = await previewLegacyMedia(); const logo = preview.imported[0]?.asset; if (!logo) return { migrated: false, branding: DEFAULT_SITE_BRANDING, preview }; const branding = await updateSiteBranding({ ...DEFAULT_SITE_BRANDING, logos: { navbarLight: logo, navbarDark: logo, footerLight: logo, footerDark: logo, squareMark: DEFAULT_SITE_BRANDING.logos.squareMark } }, actor); return { migrated: true, branding, preview } }
