import {
  MobileSession,
  MobileDevice,
  PushNotificationTemplate,
  NotificationAudience,
  DeviceActivityLog,
  MobileAppStatus,
  QRMemberCard,
  PushCategory,
} from './mobile-types'

// Mock Active Sessions
export const mockMobileSessions: MobileSession[] = [
  {
    id: 'sess-001',
    deviceId: 'dev-001',
    deviceName: 'iPhone 14 Pro',
    deviceType: 'iOS',
    lastLogin: new Date(Date.now() - 5 * 60000),
    appVersion: '2.1.0',
    status: 'active',
    isTrusted: true,
    isOnline: true,
    ipAddress: '192.168.1.105',
    location: 'Bandung, West Java',
  },
  {
    id: 'sess-002',
    deviceId: 'dev-002',
    deviceName: 'Samsung Galaxy A12',
    deviceType: 'Android',
    lastLogin: new Date(Date.now() - 12 * 60000),
    appVersion: '2.0.8',
    status: 'active',
    isTrusted: true,
    isOnline: true,
    ipAddress: '192.168.1.106',
    location: 'Garut, West Java',
    batteryLevel: 45,
  },
  {
    id: 'sess-003',
    deviceId: 'dev-003',
    deviceName: 'Xiaomi Redmi Note 11',
    deviceType: 'Android',
    lastLogin: new Date(Date.now() - 2 * 3600000),
    appVersion: '1.9.5',
    status: 'idle',
    isTrusted: false,
    isOnline: false,
    ipAddress: '192.168.1.107',
    location: 'Jakarta, Indonesia',
  },
  {
    id: 'sess-004',
    deviceId: 'dev-004',
    deviceName: 'iPad Air',
    deviceType: 'iOS',
    lastLogin: new Date(Date.now() - 24 * 3600000),
    appVersion: '2.0.8',
    status: 'suspicious',
    isTrusted: false,
    isOnline: false,
    ipAddress: '203.45.67.89',
    location: 'Unknown Location',
  },
]

// Mock Registered Devices
export const mockMobileDevices: MobileDevice[] = [
  {
    id: 'dev-001',
    userId: 'user-101',
    userName: 'Budi Santoso',
    deviceName: 'iPhone 14 Pro',
    deviceType: 'iOS',
    appVersion: '2.1.0',
    osVersion: '17.2',
    registeredDate: new Date('2023-06-15'),
    lastActive: new Date(Date.now() - 5 * 60000),
    status: 'active',
    sessions: 24,
    isTrusted: true,
  },
  {
    id: 'dev-002',
    userId: 'user-102',
    userName: 'Siti Nurhaliza',
    deviceName: 'Samsung Galaxy A12',
    deviceType: 'Android',
    appVersion: '2.0.8',
    osVersion: '12',
    registeredDate: new Date('2023-07-20'),
    lastActive: new Date(Date.now() - 12 * 60000),
    status: 'active',
    sessions: 18,
    isTrusted: true,
  },
  {
    id: 'dev-003',
    userId: 'user-103',
    userName: 'Ahmad Rifki',
    deviceName: 'Xiaomi Redmi Note 11',
    deviceType: 'Android',
    appVersion: '1.9.5',
    osVersion: '11',
    registeredDate: new Date('2023-08-10'),
    lastActive: new Date(Date.now() - 2 * 3600000),
    status: 'idle',
    sessions: 12,
    isTrusted: false,
  },
  {
    id: 'dev-005',
    userId: 'user-104',
    userName: 'Dewi Lestari',
    deviceName: 'iPhone 12',
    deviceType: 'iOS',
    appVersion: '2.1.0',
    osVersion: '16.5',
    registeredDate: new Date('2023-05-01'),
    lastActive: new Date(Date.now() - 8 * 3600000),
    status: 'active',
    sessions: 31,
    isTrusted: true,
  },
  {
    id: 'dev-006',
    userId: 'user-105',
    userName: 'Rudi Hermawan',
    deviceName: 'Realme C33',
    deviceType: 'Android',
    appVersion: '2.0.8',
    osVersion: '13',
    registeredDate: new Date('2023-09-05'),
    lastActive: new Date(Date.now() - 48 * 3600000),
    status: 'suspicious',
    sessions: 5,
    isTrusted: false,
  },
]

// Mock Push Notification Templates
export const mockNotificationTemplates: PushNotificationTemplate[] = [
  {
    id: 'tpl-001',
    name: 'New Approval Request',
    category: 'Operational',
    title: 'Permohonan Persetujuan Baru',
    body: 'Ada permohonan persetujuan baru yang memerlukan tindakan Anda dari {kecamatan}',
    deepLink: '/approvals',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'tpl-002',
    name: 'Transaction Report',
    category: 'Finance',
    title: 'Laporan Transaksi Bulanan',
    body: 'Laporan transaksi {bulan} untuk {kecamatan} telah siap ditinjau',
    deepLink: '/reports',
    createdAt: new Date('2024-01-08'),
  },
  {
    id: 'tpl-003',
    name: 'Collection Reminder',
    category: 'Reminder',
    title: 'Pengingat Pengumpulan Dana',
    body: 'Segera kumpulkan dana infak untuk periode {periode}',
    deepLink: '/collections',
    createdAt: new Date('2024-01-05'),
  },
  {
    id: 'tpl-004',
    name: 'System Announcement',
    category: 'Announcement',
    title: 'Pengumuman Sistem',
    body: '{announcement}',
    deepLink: '/announcements',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'tpl-005',
    name: 'Security Alert',
    category: 'Security',
    title: 'Peringatan Keamanan',
    body: 'Aktivitas mencurigakan terdeteksi. Silakan verifikasi akun Anda.',
    deepLink: '/security',
    createdAt: new Date('2023-12-28'),
  },
]

// Mock Notification Audiences
export const mockNotificationAudiences: NotificationAudience[] = [
  {
    id: 'aud-001',
    name: 'All Active Users',
    filters: {
      appType: 'Both',
      activeOnly: true,
    },
    count: 287,
  },
  {
    id: 'aud-002',
    name: 'PLPK Coordinators',
    filters: {
      appType: 'PLPK',
      roles: ['coordinator', 'supervisor'],
    },
    count: 45,
  },
  {
    id: 'aud-003',
    name: 'Munfiq Officers',
    filters: {
      appType: 'Munfiq',
      roles: ['officer', 'manager'],
    },
    count: 62,
  },
  {
    id: 'aud-004',
    name: 'Bandung Region',
    filters: {
      regions: ['Bandung'],
      activeOnly: true,
    },
    count: 78,
  },
]

// Mock Device Activity Logs
export const mockDeviceActivityLogs: DeviceActivityLog[] = [
  {
    id: 'log-001',
    deviceId: 'dev-001',
    action: 'login',
    timestamp: new Date(Date.now() - 5 * 60000),
    details: 'User logged in successfully',
  },
  {
    id: 'log-002',
    deviceId: 'dev-001',
    action: 'sync',
    timestamp: new Date(Date.now() - 3 * 60000),
    details: 'Data synchronized with server',
  },
  {
    id: 'log-003',
    deviceId: 'dev-002',
    action: 'login',
    timestamp: new Date(Date.now() - 12 * 60000),
    details: 'User logged in successfully',
  },
  {
    id: 'log-004',
    deviceId: 'dev-004',
    action: 'warning',
    timestamp: new Date(Date.now() - 6 * 3600000),
    details: 'Multiple failed login attempts detected',
  },
  {
    id: 'log-005',
    deviceId: 'dev-004',
    action: 'error',
    timestamp: new Date(Date.now() - 5 * 3600000),
    details: 'Session timeout due to suspicious activity',
  },
]

// Mock Mobile App Status
export const mockMobileAppStatus: MobileAppStatus = {
  activeUsers: 245,
  totalDevices: 312,
  onlineDevices: 187,
  avgBattery: 62,
  notificationDeliveryRate: 94.8,
  errorRate: 1.2,
  lastSyncTime: new Date(Date.now() - 2 * 60000),
}

// Mock QR Member Cards
export const mockQRMemberCards: QRMemberCard[] = [
  {
    id: 'qr-001',
    memberId: 'user-101',
    memberName: 'Budi Santoso',
    kecamatan: 'Bandung Utara',
    role: 'PLPK Coordinator',
    joinDate: new Date('2022-03-15'),
    isActive: true,
    qrCode: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="200" height="200"%3E%3Crect fill="white" width="200" height="200"/%3E%3C/svg%3E',
  },
  {
    id: 'qr-002',
    memberId: 'user-102',
    memberName: 'Siti Nurhaliza',
    kecamatan: 'Bandung Selatan',
    role: 'Munfiq Officer',
    joinDate: new Date('2022-06-20'),
    isActive: true,
    qrCode: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="200" height="200"%3E%3Crect fill="white" width="200" height="200"/%3E%3C/svg%3E',
  },
]
